-- Drop table if exists to ensure clean slate
DROP TABLE IF EXISTS courses;

-- Create courses table
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    category TEXT NOT NULL,
    course_name TEXT NOT NULL,
    duration TEXT NOT NULL,
    fees JSONB,
    syllabus TEXT[],
    image TEXT,
    description TEXT
);

-- Insert data
INSERT INTO courses (category, course_name, duration, fees, syllabus, image, description) VALUES
(
    'Core Computer Courses',
    'Certificate in C Programming',
    '6 Months',
    '{"admission": 1200, "monthly": 800, "total": 6000}',
    ARRAY['Intro to Programming Logic & Flowcharts', 'C Fundamentals (Variables, Data Types)', 'Control Structures (Loops, If-Else)', 'Arrays, Strings & Functions', 'Pointers & Memory Management', 'Structures & Unions', 'File Handling in C'],
    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    'Master the fundamentals of C programming, the foundation of modern computing languages.'
),
(
    'Core Computer Courses',
    'Certificate in C++ Programming',
    '6 Months',
    '{"admission": 1200, "monthly": 800, "total": 6000}',
    ARRAY['OOP Concepts (Classes, Objects)', 'Constructors & Destructors', 'Inheritance & Polymorphism', 'Function & Operator Overloading', 'Templates & Exception Handling', 'File I/O Streams'],
    'https://images.unsplash.com/photo-1518773553398-650c184e0bb3?auto=format&fit=crop&w=800&q=80',
    'Learn Object-Oriented Programming with C++ and build efficient, high-performance applications.'
),
(
    'Core Computer Courses',
    'Certificate in Java Programming',
    '6 Months',
    '{"admission": 1400, "monthly": 850, "total": 6500}',
    ARRAY['Java Basics (JVM, JDK, JRE)', 'OOPs in Java', 'Packages & Interfaces', 'Exception Handling & Multithreading', 'Java I/O & Applets', 'JDBC Connectivity'],
    'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    'Become proficient in Java, one of the most popular languages for enterprise development.'
),
(
    'Core Computer Courses',
    'Certificate in Python Programming',
    '6 Months',
    '{"admission": 1400, "monthly": 850, "total": 6500}',
    ARRAY['Python Syntax & Data Types', 'Lists, Tuples, Dictionaries', 'Functions & Modules', 'File Handling & Exception Handling', 'OOP in Python', 'Basic Libraries (NumPy intro)'],
    'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=800&q=80',
    'Start your journey with Python, the versatile language for web, data science, and automation.'
),
(
    'Core Computer Courses',
    'Certificate in C# Programming',
    '6 Months',
    '{"admission": 1600, "monthly": 850, "total": 6700}',
    ARRAY['.NET Framework Architecture', 'C# Syntax & Data Types', 'OOPs Implementation', 'Delegates & Events', 'Windows Forms Basics', 'ADO.NET Connectivity'],
    'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80',
    'Develop powerful Windows applications and games using C# and the .NET framework.'
),
(
    'Core Computer Courses',
    'Certificate in SQL Programming',
    '6 Months',
    '{"admission": 1000, "monthly": 700, "total": 5200}',
    ARRAY['RDBMS Concepts', 'DDL, DML, DCL Commands', 'Constraints & Keys', 'Joins & Subqueries', 'Views, Indexes, & Stored Procedures'],
    'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=800&q=80',
    'Master SQL to efficiently manage, query, and analyze relational databases.'
),
(
    'Core Computer Courses',
    'Certificate in DBMS',
    '6 Months',
    '{"admission": 1200, "monthly": 800, "total": 6000}',
    ARRAY['Database Architecture', 'ER Modeling', 'Normalization (1NF to BCNF)', 'Transaction Management', 'SQL Basics'],
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    'Understand the theoretical and practical aspects of Database Management Systems.'
),
(
    'Core Computer Courses',
    'Certificate in Data Structure',
    '6 Months',
    '{"admission": 1400, "monthly": 900, "total": 6800}',
    ARRAY['Arrays & Linked Lists', 'Stacks & Queues', 'Trees & Graphs', 'Sorting & Searching Algorithms', 'Hashing Techniques', 'Implementation in C/Java/Python'],
    'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=80',
    'Learn essential data structures and algorithms to write efficient and optimized code.'
),
(
    'Core Computer Courses',
    'Certificate in Computer Fundamentals',
    '6 Months',
    '{"admission": 1000, "monthly": 600, "total": 4600}',
    ARRAY['Parts of Computer (Hardware/Software)', 'Number Systems', 'Operating System Basics', 'Basic Hardware Maintenance', 'Intro to Internet & Networking'],
    'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    'Build a strong foundation in computer basics, hardware, and essential software concepts.'
),
(
    'Core Computer Courses',
    'Certificate in Operating Systems',
    '6 Months',
    '{"admission": 1000, "monthly": 600, "total": 4600}',
    ARRAY['Windows Administration', 'Linux/Unix Commands', 'File System Management', 'User & Group Management', 'Shell Scripting Basics'],
    'https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=800&q=80',
    'Dive deep into how operating systems work, including Windows administration and Linux commands.'
),
(
    'Core Computer Courses',
    'Cert. in Data Comm. & Networking',
    '6 Months',
    '{"admission": 1600, "monthly": 800, "total": 6400}',
    ARRAY['OSI & TCP/IP Models', 'IP Addressing & Subnetting', 'Network Topologies', 'Router & Switch Configuration', 'Basic Network Security'],
    'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    'Understand computer networking, from basic concepts to configuration and security.'
),
(
    'Web Technologies & Web Development',
    'React Basics',
    '6 Months',
    '{"admission": 2000, "monthly": 1800, "total": 12800}',
    ARRAY['ES6 Refresher', 'React Components & JSX', 'Props & State Management', 'Event Handling', 'Lifecycle Methods'],
    'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=800&q=80',
    'Get started with React.js, the leading library for building dynamic user interfaces.'
),
(
    'Web Technologies & Web Development',
    'Advanced React',
    '6 Months',
    '{"admission": 3000, "monthly": 2200, "total": 16200}',
    ARRAY['Hooks (useState, useEffect, etc.)', 'Context API & Redux', 'React Router', 'Performance Optimization', 'Testing React Apps'],
    'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?auto=format&fit=crop&w=800&q=80',
    'Master advanced React concepts including Hooks, State Management, and Performance Tuning.'
),
(
    'Web Technologies & Web Development',
    'Certificate in JavaScript',
    '6 Months',
    '{"admission": 3000, "monthly": 2200, "total": 16200}',
    ARRAY['JS Syntax & DOM Manipulation', 'ES6+ Features (Arrow functions, Promises)', 'Async/Await & Fetch API', 'Event Bubbling & Delegation', 'Object-Oriented JS'],
    'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?auto=format&fit=crop&w=800&q=80',
    'Deep dive into JavaScript, the language of the web, from basics to advanced asynchronous programming.'
),
(
    'Web Technologies & Web Development',
    'Certificate in TypeScript',
    '6 Months',
    '{"admission": 3000, "monthly": 2200, "total": 16200}',
    ARRAY['Types & Interfaces', 'Classes & Modules', 'Generics', 'Decorators', 'Integrating TS with React/Node'],
    'https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=800&q=80',
    'Scale your JavaScript applications with TypeScript, adding static typing and powerful tooling.'
),
(
    'Web Technologies & Web Development',
    'Web Dev using Bootstrap',
    '6 Months',
    '{"admission": 3000, "monthly": 2200, "total": 16200}',
    ARRAY['Grid System', 'Components (Navbar, Modal, Cards)', 'Utilities & Layouts', 'Customizing Bootstrap with SASS', 'Responsive Design Projects'],
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
    'Learn to build responsive, mobile-first websites quickly using the Bootstrap framework.'
),
(
    'Web Technologies & Web Development',
    'Web Dev using Tailwind',
    '6 Months',
    '{"admission": 3000, "monthly": 2200, "total": 16200}',
    ARRAY['Utility-First Fundamentals', 'Flexbox & Grid in Tailwind', 'Responsive Modifiers', 'Customizing Config', 'Building Modern UI Layouts'],
    'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=800&q=80',
    'Master Tailwind CSS to build custom, modern designs without leaving your HTML.'
),
(
    'Web Technologies & Web Development',
    'Frontend Web Development',
    '18 Months',
    '{"admission": 3000, "monthly": 1200, "total": 24600}',
    ARRAY['HTML5, CSS3, JavaScript', 'Version Control (Git)', 'Frameworks (React/Vue)', 'Responsive Design', 'Web Accessibility & SEO Basics'],
    'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?auto=format&fit=crop&w=800&q=80',
    'A comprehensive program covering all aspects of modern Frontend Development.'
),
(
    'Web Technologies & Web Development',
    'Backend Web Development',
    '18 Months',
    '{"admission": 3000, "monthly": 1200, "total": 24600}',
    ARRAY['Node.js & Express', 'Databases (MongoDB/SQL)', 'API Development (REST/GraphQL)', 'Authentication (JWT/OAuth)', 'Server Deployment'],
    'https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&w=800&q=80',
    'Learn to build robust server-side applications, APIs, and databases for web platforms.'
),
(
    'Web Technologies & Web Development',
    'Full Stack Web Development',
    '18 Months',
    '{"admission": 3500, "monthly": 1500, "total": 30500}',
    ARRAY['Complete Frontend (HTML/CSS/JS/React)', 'Complete Backend (Node/Express/DB)', 'API Integration', 'DevOps Basics (Docker/AWS)', 'Capstone Project'],
    'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    'Become a Full Stack Developer capable of building complete web solutions from front to back.'
),
(
    'Computer Certificate Courses',
    'Cert. in IT Application (CITA)',
    '6 Months',
    '{"admission": 600, "monthly": 500, "total": 3600}',
    ARRAY['Computer Fundamentals', 'MS Office (Word, Excel, PowerPoint)', 'Internet & Email', 'Basic OS Operations'],
    'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=800&q=80',
    'Learn essential IT applications including MS Office and Internet basics for daily use.'
),
(
    'Computer Certificate Courses',
    'Cert. in Information Tech (CIT)',
    '6 Months',
    '{"admission": 600, "monthly": 500, "total": 3600}',
    ARRAY['IT Concepts & Data Processing', 'Advanced Office Tools', 'Database Basics (Access)', 'Web Surfing & Security Basics'],
    'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=800&q=80',
    'Gain a solid grounding in Information Technology concepts and office productivity tools.'
),
(
    'Computer Certificate Courses',
    'Cert. in Data Entry Operator (CDEO)',
    '6 Months',
    '{"admission": 600, "monthly": 450, "total": 3300}',
    ARRAY['Typing Speed Building (Eng/Reg)', 'MS Word Formatting', 'Excel Data Entry & Basic Formulas', 'Internet Data Sourcing'],
    'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80',
    'Enhance your typing speed and accuracy, and learn efficient data entry techniques.'
),
(
    'Computer Certificate Courses',
    'Cert. in Desktop Publishing (CDTP)',
    '6 Months',
    '{"admission": 600, "monthly": 450, "total": 3300}',
    ARRAY['Adobe Photoshop (Editing)', 'CorelDraw (Vector Graphics)', 'PageMaker/InDesign', 'Scanning & Printing'],
    'https://images.unsplash.com/photo-1626785774573-4b799312c95d?auto=format&fit=crop&w=800&q=80',
    'Learn to create professional documents, designs, and layouts using industry-standard tools.'
),
(
    'Computer Certificate Courses',
    'Cert. in Computer Awareness (CCA)',
    '6 Months',
    '{"admission": 600, "monthly": 400, "total": 3000}',
    ARRAY['Intro to Computers', 'MS Paint, Notepad, WordPad', 'Basic MS Office', 'Using the Internet'],
    'https://images.unsplash.com/photo-1531297461136-82lw85e50529?auto=format&fit=crop&w=800&q=80',
    'A beginner-friendly course to get comfortable with using computers and the internet.'
),
(
    'Computer Certificate Courses',
    'Cert. in Internet Application (CIA)',
    '6 Months',
    '{"admission": 600, "monthly": 450, "total": 3300}',
    ARRAY['Browsers & Search Engines', 'Email Clients & Etiquette', 'Online Safety & Payments', 'Cloud Storage (Drive/Dropbox)'],
    'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=800&q=80',
    'Master the internet: browsing, emailing, online safety, and using cloud services effectively.'
),
(
    'Computer Certificate Courses',
    'Cert. in Computer Fundamentals (CCF)',
    '6 Months',
    '{"admission": 600, "monthly": 450, "total": 3300}',
    ARRAY['Hardware Components', 'Software Installation', 'Windows Settings & Control Panel', 'Virus Scanning & Maintenance'],
    'https://images.unsplash.com/photo-1591405351990-4726e331f141?auto=format&fit=crop&w=800&q=80',
    'Understand the core fundamentals of computer hardware, software, and system maintenance.'
),
(
    'Computer Certificate Courses',
    'Cert. in Office Automation (COA)',
    '6 Months',
    '{"admission": 600, "monthly": 500, "total": 3600}',
    ARRAY['Advanced Word Processing', 'Spreadsheet Management', 'Presentation Skills', 'Office Peripherals Usage'],
    'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80',
    'Streamline office tasks with advanced automation skills in word processing and spreadsheets.'
),
(
    'Computer Certificate Courses',
    'Cert. in Typing Master (CTM)',
    '6 Months',
    '{"admission": 600, "monthly": 300, "total": 2400}',
    ARRAY['Touch Typing Techniques', 'Speed & Accuracy Drills', 'Numeric Keypad Training', 'Typing Games & Tests'],
    'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80',
    'Become a typing pro with touch typing techniques and speed building drills.'
),
(
    'Computer Certificate Courses',
    'Cert. in Financial Accounting (CFA)',
    '6 Months',
    '{"admission": 700, "monthly": 500, "total": 3700}',
    ARRAY['Basic Accounting Principles', 'Tally ERP 9 / Prime Intro', 'Vouchers & Ledgers', 'GST Basics'],
    'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80',
    'Learn the basics of financial accounting and get started with popular accounting software.'
),
(
    'Computer Certificate Courses',
    'Cert. in Web Design (CWD)',
    '6 Months',
    '{"admission": 1200, "monthly": 600, "total": 4800}',
    ARRAY['HTML Structure', 'CSS Styling', 'Basic JavaScript', 'Website Publishing'],
    'https://images.unsplash.com/photo-1547658719-da2b51169166?auto=format&fit=crop&w=800&q=80',
    'Create beautiful websites by learning the essential building blocks: HTML, CSS, and basic JS.'
),
(
    'Computer Certificate Courses',
    'Cert. in Language (CCL)',
    '6 Months',
    '{"admission": 1200, "monthly": 700, "total": 5400}',
    ARRAY['Programming Logic', 'Syntax of chosen language (C/Python)', 'Basic algorithms', 'Simple Application Dev'],
    'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=800&q=80',
    'Get introduced to programming logic and syntax in a chosen language like C or Python.'
),
(
    'Computer Certificate Courses',
    'Cert. in Accounting (Tally)',
    '6 Months',
    '{"admission": 1200, "monthly": 600, "total": 4800}',
    ARRAY['Advanced Tally Features', 'Inventory Management', 'Payroll Accounting', 'Taxation & E-Filing'],
    'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=800&q=80',
    'Master Tally for comprehensive business accounting, inventory, and taxation.'
),
(
    'Computer Diploma Courses',
    'Diploma in IT Application (DITA)',
    '12 Months',
    '{"admission": 1000, "monthly": 500, "total": 7000}',
    ARRAY['Adv. Computer Concepts', 'Programming Logic', 'Web Tech Basics', 'Database Management', 'Project Work'],
    'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    'A one-year diploma covering advanced computer concepts, programming, and web basics.'
),
(
    'Computer Diploma Courses',
    'Diploma in IT (DIT)',
    '12 Months',
    '{"admission": 1000, "monthly": 500, "total": 7000}',
    ARRAY['IT Systems & Architecture', 'Networking Fundamentals', 'Programming (C/C++)', 'System Analysis & Design'],
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
    'Study IT systems, networking, and programming in depth with this diploma program.'
),
(
    'Computer Diploma Courses',
    'Diploma in Comp Application (DCA)',
    '12 Months',
    '{"admission": 1000, "monthly": 500, "total": 7000}',
    ARRAY['Computer Fundamentals & OS', 'MS Office Suite', 'DTP Basics (Photoshop)', 'Tally Basics', 'Internet & HTML'],
    'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    'A well-rounded diploma covering office apps, DTP, accounting, and internet basics.'
),
(
    'Computer Diploma Courses',
    'Diploma in Comp Programming (DCP)',
    '12 Months',
    '{"admission": 1200, "monthly": 1000, "total": 13200}',
    ARRAY['C, C++, & Java/Python', 'Data Structures', 'Database (SQL)', 'Software Engineering Concepts'],
    'https://images.unsplash.com/photo-1555099962-4199c345e5dd?auto=format&fit=crop&w=800&q=80',
    'Specialize in programming with this diploma, covering multiple languages and software engineering.'
),
(
    'Computer Diploma Courses',
    'Diploma in Web Designing (DWD)',
    '12 Months',
    '{"admission": 1200, "monthly": 650, "total": 9000}',
    ARRAY['HTML5, CSS3, JS', 'Responsive Frameworks', 'UI/UX Principles', 'Graphics for Web (Photoshop)', 'Live Project'],
    'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
    'Learn to design professional, responsive websites with UI/UX principles and graphics tools.'
),
(
    'Computer Diploma Courses',
    'Diploma in Computer Science (DCS)',
    '12 Months',
    '{"admission": 1500, "monthly": 1450, "total": 18900}',
    ARRAY['CS Fundamentals', 'Digital Electronics', 'OS Internals', 'Advanced Programming', 'Networking & DBMS'],
    'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    'An extensive diploma covering the core subjects of Computer Science and engineering.'
),
(
    'Computer Diploma Courses',
    'Diploma in Hardware & Net (DCHN)',
    '12 Months',
    '{"admission": 1000, "monthly": 600, "total": 8200}',
    ARRAY['PC Assembly/Disassembly', 'Troubleshooting & Repair', 'Network Cabling & Config', 'Server Administration Basics'],
    'https://images.unsplash.com/photo-1597852074816-d933c7bd2617?auto=format&fit=crop&w=800&q=80',
    'Become a customized hardware and networking professional with troubleshooting skills.'
),
(
    'Computer Diploma Courses',
    'Dip. Office Auto. & Prog. (DOACP)',
    '12 Months',
    '{"admission": 1200, "monthly": 800, "total": 10800}',
    ARRAY['Office Automation Tools', 'Programming in C', 'Web Scripting (HTML/JS)', 'Financial Accounting'],
    'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
    'Combine office automation proficiency with programming and web scripting skills.'
),
(
    'Computer Diploma Courses',
    'Diploma in Office Management (DOM)',
    '12 Months',
    '{"admission": 1000, "monthly": 500, "total": 7000}',
    ARRAY['Office Procedures', 'Business Communication', 'Computer Apps for Management', 'Data Management'],
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80',
    'Prepare for an administrative role with skills in office procedures and management apps.'
),
(
    'Computer Diploma Courses',
    'Diploma in Desktop Publishing (DDTP)',
    '12 Months',
    '{"admission": 1000, "monthly": 500, "total": 7000}',
    ARRAY['Advanced Graphic Design', 'Typography & Layout', 'Printing Technology', 'Project Portfolio'],
    'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?auto=format&fit=crop&w=800&q=80',
    'Master graphic design and layout for print media with advanced DTP training.'
),
(
    'Computer Diploma Courses',
    'Dip. Data Entry & Digital Lang (DDL)',
    '12 Months',
    '{"admission": 1200, "monthly": 800, "total": 10800}',
    ARRAY['Adv. Data Entry Skills', 'Digital Documentation', 'Regional Language Computing', 'Transcription Basics'],
    'https://images.unsplash.com/photo-1589652717521-10c0d092dea9?auto=format&fit=crop&w=800&q=80',
    'Become proficient in high-speed data entry and digital language computing.'
),
(
    'Computer Diploma Courses',
    'Dip. Prof. Accounting & Tally (DPAT)',
    '12 Months',
    '{"admission": null, "monthly": null, "total": null}',
    ARRAY['Financial Reporting', 'Adv. Taxation (GST/TDS)', 'Banking & Payroll', 'Corporate Accounts'],
    'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80',
    'Professional diploma focused on advanced accounting, taxation, and Tally.'
),
(
    'Computer Diploma Courses',
    'Diploma in Cyber Security (DCSEH)',
    '12 Months',
    '{"admission": null, "monthly": null, "total": null}',
    ARRAY['Network Security', 'Ethical Hacking Basics', 'Cryptography', 'Cyber Laws & Forensics'],
    'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    'Enter the world of cybersecurity with skills in network security and ethical hacking.'
),
(
    'Computer Diploma Courses',
    'Diploma in Digital Marketing (DDM)',
    '12 Months',
    '{"admission": null, "monthly": null, "total": null}',
    ARRAY['SEO & SEM', 'Social Media Marketing', 'Content Strategy', 'Analytics & Reporting'],
    'https://images.unsplash.com/photo-1533750516457-a7f992034fec?auto=format&fit=crop&w=800&q=80',
    'Learn to market brands online with SEO, SMM, and digital content strategies.'
),
(
    'Computer Advance Diploma Courses',
    'Adv Diploma in Comp App (ADCA)',
    '12 Months',
    '{"admission": 1500, "monthly": 650, "total": 9300}',
    ARRAY['DCA Syllabus +', 'Advanced Database', 'Programming Elective', 'Project Management'],
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    'Advanced level diploma in computer applications including database and project management.'
),
(
    'Computer Advance Diploma Courses',
    'Adv Dip Office Auto & Prog (ADOACP)',
    '18 Months',
    '{"admission": 1500, "monthly": 850, "total": 16800}',
    ARRAY['DOACP Syllabus +', 'Advanced Programming (Java/C#)', 'Web App Development'],
    'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    'Comprehensive course combining advanced office automation with high-level programming.'
),
(
    'Computer Advance Diploma Courses',
    'Adv Diploma in IT (ADIT)',
    '18 Months',
    '{"admission": 1200, "monthly": 500, "total": 10200}',
    ARRAY['DIT Syllabus +', 'Advanced Networking', 'Enterprise Resource Planning (ERP)', 'Cloud Computing Intro'],
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    'Advanced IT diploma covering networking, ERP systems, and cloud computing basics.'
),
(
    'Computer Advance Diploma Courses',
    'Adv Diploma in DTP (ADDTP)',
    '18 Months',
    '{"admission": 1000, "monthly": 550, "total": 10900}',
    ARRAY['DDTP Syllabus +', '3D Modeling Basics', 'Video Editing Basics', 'Digital Illustration'],
    'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80',
    'Advanced DTP course with multimedia skills like 3D modeling and video editing.'
),
(
    'Computer Advance Diploma Courses',
    'Adv Dip Hardware & Net (ADCHN)',
    '18 Months',
    '{"admission": 1200, "monthly": 600, "total": 12000}',
    ARRAY['DCHN Syllabus +', 'Cisco Routing/Switching', 'Wireless Networking', 'Network Security Admin'],
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    'Expert level hardware and networking training including Cisco tech and security.'
),
(
    'Computer Advance Diploma Courses',
    'Adv Dip in Office Mgmt (ADOM)',
    '18 Months',
    '{"admission": 1100, "monthly": 550, "total": 11000}',
    ARRAY['Office Admin & HR', 'Adv. Tally & Payroll', 'Soft Skills & Personality Dev', 'E-Office Management'],
    'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80',
    'Advanced office management with HR, soft skills, and digital office administration.'
),
(
    'Computer Advance Diploma Courses',
    'Adv Dip in Web Designing (ADWD)',
    '12 Months',
    '{"admission": 1400, "monthly": 800, "total": 11000}',
    ARRAY['DWD Syllabus +', 'Backend Basics (PHP/Node)', 'CMS (WordPress)', 'E-Commerce Design'],
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    'Advanced web designing including backend concepts, CMS, and e-commerce.'
),
(
    'Kids Computer Courses (Class I - X)',
    'PP1 & PP2',
    '12 Months',
    '{"admission": 500, "monthly": 300, "total": 4100}',
    ARRAY['Recognition of Computer Parts', 'Mouse Control Games', 'Basic Keyboard Introduction'],
    'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80',
    'A playful introduction to computers for the youngest learners.'
),
(
    'Kids Computer Courses (Class I - X)',
    'Learning School Comp (Class 1-5)',
    '12 Months',
    '{"admission": 500, "monthly": 300, "total": 4100}',
    ARRAY['Paint & Drawing', 'Typing Practice', 'Intro to Windows', 'Educational Games'],
    'https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=800&q=80',
    'Computer learning made fun: painting, typing, and educational games for primary kids.'
),
(
    'Kids Computer Courses (Class I - X)',
    'Learning School Comp (Class 6-7)',
    '12 Months',
    '{"admission": 500, "monthly": 350, "total": 4700}',
    ARRAY['MS Word & PowerPoint', 'Internet Surfing', 'Basic HTML', 'Logical Reasoning'],
    'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    'Step up to real applications like Word, PowerPoint, and basic web concepts.'
),
(
    'Kids Computer Courses (Class I - X)',
    'Learning School Comp (Class 8-9)',
    '12 Months',
    '{"admission": 500, "monthly": 400, "total": 5300}',
    ARRAY['Advanced Office Tools', 'Excel Formulas', 'Coding Basics (Scratch/Python)', 'Graphic Editing Basics'],
    'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    'Prepare for the future with Excel, basic coding, and graphic editing skills.'
),
(
    'Kids Computer Courses (Class I - X)',
    'Foundation Cert. (FCCE)',
    '12 Months',
    '{"admission": 600, "monthly": 400, "total": 5400}',
    ARRAY['Comprehensive Computer Literacy', 'Office Suite Mastery', 'Internet Research', 'Digital Safety'],
    'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    'A solid foundation certificate in computer literacy and digital safety.'
),
(
    'Kids Computer Courses (Class I - X)',
    'Creative Computing (CCK)',
    '6 Months',
    '{"admission": 500, "monthly": 300, "total": 2300}',
    ARRAY['Digital Art', 'Storytelling with Slides', 'Animation Basics', 'Coding Logic'],
    'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    'Unleash creativity with digital art, animation, and logic games.'
);
