-- Create tables for Course Structure

-- 1. Course Modules
create table if not exists public.course_modules (
    id bigint generated by default as identity primary key,
    course_id bigint references public.courses(id) on delete cascade not null,
    title text not null,
    description text,
    sort_order integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Course Topics
create table if not exists public.course_topics (
    id bigint generated by default as identity primary key,
    module_id bigint references public.course_modules(id) on delete cascade not null,
    title text not null,
    description text,
    sort_order integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Student Topic Progress
create table if not exists public.student_topic_progress (
    id bigint generated by default as identity primary key,
    student_id uuid references public.profiles(id) on delete cascade not null,
    topic_id bigint references public.course_topics(id) on delete cascade not null,
    status text default 'completed' check (status in ('completed', 'pending')),
    completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
    completed_by uuid references public.profiles(id), -- Teacher who marked it
    unique(student_id, topic_id)
);

-- Enable RLS (Optional but recommended, allowing public read for now to simplify)
alter table public.course_modules enable row level security;
alter table public.course_topics enable row level security;
alter table public.student_topic_progress enable row level security;

-- Policies (Simplified for development)
-- Allow read access to everyone (authenticated)
create policy "Enable read access for all users" on public.course_modules for select using (auth.role() = 'authenticated');
create policy "Enable read access for all users" on public.course_topics for select using (auth.role() = 'authenticated');
create policy "Enable read access for all users" on public.student_topic_progress for select using (auth.role() = 'authenticated');

-- Allow insert/update/delete for admins/teachers (checking profile role efficiently is harder in RLS without claims, 
-- assuming app logic handles strict checks or simple auth.uid check if possible. 
-- For now, open write for authenticated to unblock dev, ideally should restrict to role='admin'/'teacher')
create policy "Enable write access for authenticated users" on public.course_modules for all using (auth.role() = 'authenticated');
create policy "Enable write access for authenticated users" on public.course_topics for all using (auth.role() = 'authenticated');
create policy "Enable write access for authenticated users" on public.student_topic_progress for all using (auth.role() = 'authenticated');
