-- 1. Updates to Courses Table
ALTER TABLE courses 
ADD COLUMN IF NOT EXISTS duration_months INTEGER DEFAULT 6;

-- 2. New Table: Course Topics (Syllabus)
CREATE TABLE IF NOT EXISTS course_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    topic_name TEXT NOT NULL,
    is_completed BOOLEAN DEFAULT false,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. New Table: Class Schedules (Recurring Rules)
CREATE TABLE IF NOT EXISTS class_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    day_of_week TEXT NOT NULL, -- 'Monday', 'Wednesday', etc.
    start_time TIME NOT NULL,
    duration_minutes INTEGER DEFAULT 60,
    room_id TEXT, -- Optional
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. New Table: Calendar Events (Actual Instances)
CREATE TABLE IF NOT EXISTS calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT REFERENCES class_schedules(id) ON DELETE SET NULL, -- Link to rule
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE, -- Direct link for easy querying
    title TEXT NOT NULL,
    start_datetime TIMESTAMP WITH TIME ZONE NOT NULL,
    end_datetime TIMESTAMP WITH TIME ZONE NOT NULL,
    event_type TEXT DEFAULT 'class', -- 'class', 'exam', 'holiday'
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Enable RLS (Row Level Security) - Optional but recommended
ALTER TABLE course_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;

-- create policies (public access for now for simplicity, refine as needed)
CREATE POLICY "Public read for course_topics" ON course_topics FOR SELECT USING (true);
CREATE POLICY "Admins/Teachers update course_topics" ON course_topics FOR ALL USING (true); -- refine logic later

CREATE POLICY "Public read for class_schedules" ON class_schedules FOR SELECT USING (true);
CREATE POLICY "Admins/Teachers update class_schedules" ON class_schedules FOR ALL USING (true);

CREATE POLICY "Public read for calendar_events" ON calendar_events FOR SELECT USING (true);
CREATE POLICY "Admins/Teachers update calendar_events" ON calendar_events FOR ALL USING (true);
