-- Add short_code to courses table
ALTER TABLE courses ADD COLUMN IF NOT EXISTS short_code TEXT;

-- Create classes table
CREATE TABLE IF NOT EXISTS classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  batch_name TEXT NOT NULL,
  batch_number INTEGER NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 30,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add class_id to enrollments table
ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS class_id BIGINT REFERENCES classes(id) ON DELETE SET NULL;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_classes_course_id ON classes(course_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_class_id ON enrollments(class_id);

-- Enable Row Level Security
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;

-- Policies
-- Allow read access to everyone (or restricted to auth/students if preferred, but usually 'true' for reading classes is fine for this app context)
CREATE POLICY "Enable read access for all users" ON classes FOR SELECT USING (true);

-- Allow write access to authenticated users (Admins/Teachers)
-- Assuming 'authenticated' role is sufficient for now based on existing patterns
CREATE POLICY "Enable insert for authenticated users only" ON classes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only" ON classes FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only" ON classes FOR DELETE USING (auth.role() = 'authenticated');
